[build]
publish = "public"
command = "hugo --gc --minify && npx pagefind --site \"public\""

[context.production.environment]
HUGO_VERSION = "v0.134.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo && npx pagefind --site \"public\""

[context.split1.environment]
HUGO_VERSION = "v0.134.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL && npx pagefind --site \"public\""

[context.deploy-preview.environment]
HUGO_VERSION = "v0.134.3"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL && npx pagefind --site \"public\""

[context.branch-deploy.environment]
HUGO_VERSION = "v0.134.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

